/* Copyright © 2018 eWorkplace Apps (https://www.eworkplaceapps.com/). All Rights Reserved.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * 
 * Author: Atul Badgujar <abadgujar@batchmaster.com>
 * Date: 1 Nov 2019
 * 
 * Contributor/s: Nitin Jain
 * Last Updated On: 1 Nov 2019
 */

using System;
using System.Collections.Generic;
using System.Text;

namespace ewApps.Core.BaseService {    

        /// <summary>
        /// Entity identification key to identify the Entity uniquely.
        /// </summary>
        [Flags]
        public enum EntityTypeEnum {
        App = 1,
        AppService = 2,
        AppServiceAccountDetail = 3,
        AppServiceAttribute = 4,
        AppUserTypeLinking = 5,
        CustomerAppServiceLinking = 6,
        SubscriptionPlan = 7,
        SubscriptionPlanService = 8,
        SubscriptionPlanServiceAttribute = 9,
        Tenant = 10,
        TenantAppServiceLinking = 11,
        TenantLinking = 12,
        TenantSubscription = 13,
        TenantUser = 14,
        TenantUserAppLastAccessInfo = 15,
        TenantUserAppLinking = 16,
        Theme = 17,
        UserTenantLinking = 18,
        ASNotification = 19,
        Business = 20,
        BusinessAddress = 21,
        Customer = 22,
        CustomerAccountDetail = 23,
        Favorite = 24,
        LevelTransitionHistory = 25,
        Notes = 26,
        Platform = 27,
        Portal = 28,
        PortalAppLinking = 29,
        PubBusinessSubsPlan = 30,
        PubBusinessSubsPlanAppService = 31,
        Publisher = 32,
        PublisherAddress = 33,
        PublisherAppSetting = 34,
        Role = 35,
        RoleLinking = 36,
        Support = 36,
        SupportComment = 37,
        SupportGroup = 38,
        SupportTicket = 39,
        TenantAppLinking = 40,
        TenantUserAppPreference = 41,
        TokenInfo = 42,
        ViewSettings = 43,
        BAARInvoice = 44,
        BAARinvoiceAttachment = 45,
        BAARInvoiceItem = 46,
        BAASN = 47,
        BAASNAttachment = 48,
        BAASNItem = 49,
        BAContract = 50,
        BAContractAttachment = 51,
        BAContractItem = 52,
        BACustomer = 53,
        BACustomerAddress = 54,
        BACustomerContact = 55,
        BACustomerPaymentDetail = 56,
        BADelivery = 57,
        BADeliveryAttachment = 58,
        BADeliveryItem = 59,
        BAItemMaster = 60,
        BAItemMasterAttachment = 61,
        BAPurchaseInquiry = 62,
        BAPurchaseInquiryItem = 63,
        BAPurchaseOrder = 64,
        BAPurchaseOrderItem = 65,
        BASalesOrder = 66,
        BASalesOrderAttachment = 67,
        BASalesOrderItem = 68,
        BASalesQuotation = 69,
        BASalesQuotationAttachment = 70,
        BASalesQuotationItem = 71,
        ERPConnector = 72,
        ERPConnectorConfig = 73,
        SyncHistory = 74,
        SyncTimeLog = 75,
        AppDeeplink = 76,
        AppDeeplinkAccessLog = 77,
        DMDocument = 78,
        DMDocumentFolderLinking = 79,
        DMDocumentUser = 80,
        DMDocumentVersion = 81,
        DMFileStorage = 82,
        DMFolder = 83,
        DMThumbnail = 84,
        DocumentCurrency = 85,
        EmailDeliveryLog = 86,
        EmailQueue = 87,
        EntityThumbnail = 88,
        ScheduledJob = 89,
        ScheduledJobLog = 90,
        Scheduler = 91,
        SMSDeliveryLog = 92,
        SMSQueue = 93,
        UniqueIdentityGenerator = 94,
        WebhookClientEventQueue = 95,
        UserSession = 96,
        WebhookClientSubscription = 97,
        WebhookEventDeliveryLog = 98,
        WebhookEventQueue = 99,
        WebhookServer = 100,
        WebhookSubscription = 101,
        __EFMigrationsHistory = 102,
        Payment = 103,
        PaymentInvoiceLinking = 104,
        PaymentLog = 105,
        PreAuthPayment = 106,
        RecurringPayment = 107,
        TSYSTransaction = 108,
        RecurringPaymentLog = 109,
        TSYSMerchant = 110,
        TSYSTransactionStatus = 111,
        VCCustomer = 112,
        VCMerchant = 113,
        VCMerchantStatusToken = 114,
        VCPayment = 115,
        VCTransaction = 116,
        VCTransactionStatus = 117,
        SAPAppConnection = 118,
        Shipments = 119,
        ShipperAccount = 120,
        ShipperDefaults = 121,
        CarrierPackageDetail = 122,
        CarrierPackageLinking = 123,
        FavouriteShipmentPkgSetting = 124,
        PackageMaster = 125,
        SalesOrderPkg = 126,
        SalesOrderPkgItem = 127,
        Shipment = 128,
        ShipmentItem = 129,
        ShipmentPkgItem = 130,
        VerifiedAddress = 131
        

    }
}
