// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ewApps.Core.UserSessionService;

namespace ewApps.Core.UserSessionService.Migrations
{
    [DbContext(typeof(UserSessionDBContext))]
    partial class UserSessionDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ewApps.Core.UserSessionService.UserSession", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppId");

                    b.Property<string>("IdentityServerId")
                        .HasMaxLength(100);

                    b.Property<string>("IdentityToken")
                        .HasMaxLength(4000);

                    b.Property<string>("Subdomain")
                        .HasMaxLength(100);

                    b.Property<Guid>("TenantId");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("TenantUserId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("UserType");

                    b.HasKey("ID");

                    b.ToTable("UserSession","core");
                });
#pragma warning restore 612, 618
        }
    }
}
