// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ewApps.Core.EmailService;

namespace ewApps.Core.EmailService.Migrations
{
    [DbContext(typeof(EmailDBContext))]
    partial class EmailDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ewApps.Core.EmailService.EmailDeliveryLog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActualDeliveryTime");

                    b.Property<Guid>("ApplicationId");

                    b.Property<string>("BCC")
                        .HasMaxLength(100);

                    b.Property<string>("CC")
                        .HasMaxLength(100);

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<int>("DeliverySubType");

                    b.Property<int>("DeliveryType");

                    b.Property<string>("MessagePart1")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.Property<string>("MessagePart2")
                        .HasMaxLength(4000);

                    b.Property<Guid>("NotificationId");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ReplyTo")
                        .HasMaxLength(100);

                    b.Property<DateTime>("ScheduledDeliveryTime");

                    b.Property<string>("Sender")
                        .HasMaxLength(100);

                    b.Property<string>("SenderKey")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("SenderName")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("EmailDeliveryLog","core");
                });

            modelBuilder.Entity("ewApps.Core.EmailService.EmailQueue", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ApplicationId");

                    b.Property<string>("BCC")
                        .HasMaxLength(100);

                    b.Property<string>("CC")
                        .HasMaxLength(100);

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<int>("DeliverySubType");

                    b.Property<DateTime>("DeliveryTime");

                    b.Property<int>("DeliveryType");

                    b.Property<string>("MessagePart1")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.Property<string>("MessagePart2")
                        .HasMaxLength(4000);

                    b.Property<Guid>("NotificationId");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ReplyTo")
                        .HasMaxLength(100);

                    b.Property<string>("Sender")
                        .HasMaxLength(100);

                    b.Property<string>("SenderKey")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("SenderName")
                        .HasMaxLength(100);

                    b.Property<int>("State");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("EmailQueue","core");
                });
#pragma warning restore 612, 618
        }
    }
}
