// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ewApps.Core.Money;

namespace ewApps.Core.Money.Migrations
{
    [DbContext(typeof(DocumentCurrencyDBContext))]
    [Migration("20190904100529_initdbmoney33")]
    partial class initdbmoney33
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ewApps.Core.Money.DocumentCurrency", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AgentAmount")
                        .HasColumnType("decimal (18,5)");

                    b.Property<int>("AgentCurrencyCode");

                    b.Property<decimal>("ApproxConversionRate")
                        .HasColumnType("decimal (18,5)");

                    b.Property<DateTime>("CreationDate");

                    b.Property<decimal>("DocumentAmount")
                        .HasColumnType("decimal (18,5)");

                    b.Property<int>("DocumentCurrencyCode");

                    b.Property<Guid>("DocumentId");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100);

                    b.Property<decimal>("FinalConversionRate")
                        .HasColumnType("decimal (18,5)");

                    b.Property<DateTime>("SettlementDate");

                    b.HasKey("ID");

                    b.ToTable("DocumentCurrency","core");
                });
#pragma warning restore 612, 618
        }
    }
}
