// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ewApps.AppMgmt.Data;

namespace ewApps.AppMgmt.Data.Migrations
{
    [DbContext(typeof(AppMgmtDbContext))]
    [Migration("20190924131718_initdb15677")]
    partial class initdb15677
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ewApps.AppMgmt.Entity.App", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("AppKey")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("AppScope");

                    b.Property<int>("AppSubscriptionMode");

                    b.Property<bool>("Constructed");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("InactiveComment")
                        .HasMaxLength(4000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("ThemeId");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("App","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.AppService", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<Guid>("AppId");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ServiceKey")
                        .HasMaxLength(20);

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("AppService","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.AppServiceAccountDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountJson");

                    b.Property<Guid>("AppId");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<Guid>("EntityId");

                    b.Property<int>("EntityType");

                    b.Property<Guid>("ServiceAttributeId");

                    b.Property<Guid>("ServiceId");

                    b.Property<Guid>("TenantId");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("AppServiceAccountDetail","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.AppServiceAttribute", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<Guid>("AppServiceId");

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(20);

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("AppServiceAttribute","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.AppUserTypeLinking", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppId");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<int>("PartnerType");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int>("UserType");

                    b.HasKey("ID");

                    b.ToTable("AppUserTypeLinking","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.CustomerAppServiceLinking", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppId");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<Guid>("CustomerId");

                    b.Property<bool>("Deleted");

                    b.Property<Guid>("ServiceAttributeId");

                    b.Property<Guid>("ServiceId");

                    b.Property<Guid>("TenantId");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("CustomerAppServiceLinking","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<bool>("AllowUnlimitedShipment");

                    b.Property<bool>("AllowUnlimitedTransaction");

                    b.Property<Guid>("AppId");

                    b.Property<bool>("AutoRenewal");

                    b.Property<int?>("BusinessUserCount");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("CustomerUserCount");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("OneTimePlan");

                    b.Property<string>("OtherFeatures")
                        .HasMaxLength(4000);

                    b.Property<int>("PaymentCycle");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("PriceInDollar")
                        .HasColumnType("decimal(18,5)");

                    b.Property<int?>("ShipmentCount");

                    b.Property<int?>("ShipmentUnit");

                    b.Property<DateTime>("StartDate");

                    b.Property<Guid>("TenantId");

                    b.Property<int>("Term");

                    b.Property<int>("TermUnit");

                    b.Property<int>("TransactionCount");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int?>("UserPerCustomerCount");

                    b.HasKey("ID");

                    b.ToTable("SubscriptionPlan","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.SubscriptionPlanService", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppServiceId");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<Guid>("SubscriptionPlanId");

                    b.Property<Guid>("TenantId");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("SubscriptionPlanService","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.SubscriptionPlanServiceAttribute", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppServiceAttributeId");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<Guid>("SubscriptionPlanId");

                    b.Property<Guid>("SubscriptionPlanServiceId");

                    b.Property<Guid>("TenantId");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("SubscriptionPlanServiceAttribute","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.Tenant", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Deleted");

                    b.Property<string>("IdentityNumber")
                        .IsRequired();

                    b.Property<Guid?>("InvitedBy");

                    b.Property<DateTime?>("InvitedOn");

                    b.Property<DateTime?>("JoinedOn");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LogoUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(4000);

                    b.Property<string>("SubDomainName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("TenantType");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("VarId")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Tenant","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.TenantAppServiceLinking", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppId");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<Guid>("ServiceAttributeId");

                    b.Property<Guid>("ServiceId");

                    b.Property<Guid>("TenantId");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("TenantAppServiceLinking","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.TenantLinking", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BusinessPartnerTenantId");

                    b.Property<Guid?>("BusinessTenantId");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<Guid?>("PlatformTenantId");

                    b.Property<Guid?>("PublisherTenantId");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("TenantLinking","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.TenantSubscription", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppId");

                    b.Property<bool>("AutoRenewal")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("BusinessUserCount");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int?>("CustomerUserCount");

                    b.Property<bool>("CustomizeSubscription")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("Deleted");

                    b.Property<string>("InactiveComment")
                        .HasMaxLength(4000);

                    b.Property<Guid>("LogoThumbnailId");

                    b.Property<bool>("OneTimePlan");

                    b.Property<int>("PaymentCycle");

                    b.Property<decimal>("PriceInDollar")
                        .HasColumnType("decimal(18,5)");

                    b.Property<int?>("ShipmentCount");

                    b.Property<int?>("ShipmentUnit");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(1);

                    b.Property<Guid>("SubscriptionPlanId");

                    b.Property<DateTime>("SubscriptionStartDate");

                    b.Property<DateTime>("SubscriptionStartEnd");

                    b.Property<Guid>("SystemConfId");

                    b.Property<Guid>("TenantId");

                    b.Property<int>("Term");

                    b.Property<Guid>("ThemeId");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int?>("UserPerCustomerCount");

                    b.HasKey("ID");

                    b.ToTable("TenantSubscription","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.TenantUser", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(4000);

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(20);

                    b.Property<Guid>("IdentityUserId");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("TenantUser","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.TenantUserAppLastAccessInfo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppId");

                    b.Property<string>("Browser")
                        .HasMaxLength(20);

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Language")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LoginDateTime");

                    b.Property<string>("Region")
                        .HasMaxLength(20);

                    b.Property<Guid>("TenantId");

                    b.Property<Guid>("TenantUserId");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(20);

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("TenantUserAppLastAccessInfo","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.TenantUserAppLinking", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<Guid>("AppId");

                    b.Property<Guid?>("BusinessPartnerTenantId");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<Guid?>("InvitedBy");

                    b.Property<DateTime?>("InvitedOn");

                    b.Property<DateTime?>("JoinedDate");

                    b.Property<int>("Status");

                    b.Property<Guid>("TenantId");

                    b.Property<Guid>("TenantUserId");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int>("UserType");

                    b.HasKey("ID");

                    b.ToTable("TenantUserAppLinking","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.Theme", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<string>("PreviewImageUrl")
                        .IsRequired();

                    b.Property<string>("ThemeKey")
                        .IsRequired();

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("Theme","am");
                });

            modelBuilder.Entity("ewApps.AppMgmt.Entity.UserTenantLinking", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BusinessPartnerTenantId");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("Deleted");

                    b.Property<bool>("IsPrimary");

                    b.Property<int?>("PartnerType");

                    b.Property<Guid>("TenantId");

                    b.Property<Guid>("TenantUserId");

                    b.Property<Guid>("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<int>("UserType");

                    b.HasKey("ID");

                    b.ToTable("UserTenantLinking","am");
                });

            modelBuilder.Entity("ewApps.Core.DMService.ThumbnailAddAndUpdateDTO", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DocumentFileName");

                    b.Property<double>("Duration");

                    b.Property<int>("MediaType");

                    b.Property<int>("TempId");

                    b.HasKey("ID");

                    b.HasAlternateKey("TempId");

                    b.ToTable("ThumbnailAddAndUpdateDTO");
                });
#pragma warning restore 612, 618
        }
    }
}
